# Generated by Django 2.1 on 2021-06-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_auto_20210620_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
