# Generated by Django 3.2 on 2022-10-27 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('update_dt',)},
        ),
    ]
