# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordertransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertransaction',
            name='type',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
