# Generated by Django 2.1 on 2021-06-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210620_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertransaction',
            name='order',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='OrderTransaction',
        ),
    ]
