# Generated by Django 4.2 on 2023-08-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_ip_alter_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
